test_shutter_position:
  name: "Test Shutter Position"
  min: 0
  max: 100
  step: 1
  initial: 0
  unit_of_measurement: "%"

test_shutter_tilt:
  name: "Test Shutter Tilt"
  min: 0
  max: 100
  step: 1
  initial: 0
  unit_of_measurement: "%"
